#!/bin/sh
#
# Copyright (c) 2010 Linagora
# Patrick Guiran <patrick.guiran@linagora.com>
# http://github.com/Tauop/sshGate
#
# sshGate is free software, you can redistribute it and/or modify
# it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# sshGate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

usage () {
  echo "usage:"
  echo "    send : $0 <file1> ... <file2> <target>:[<rep/file>]"
  echo " receive :  $0 <target>:[<rep/file>] <file or directory>"
  exit 1
}

# check the configuration
sshgate-client-configure

is_target_arg() {
  echo "$1" | grep ':' >/dev/null 2>/dev/null
  [ $? -eq 0 ] && echo 'true' || echo 'false'
}

if [ $# -lt 2 ]; then
  echo "ERROR: bad arguments"
  usage
fi

action=
target_host=
target_location=
local_location=
scp_opt=

# get options
while [ true ]; do
  case "$1" in
    -[1246BCpqrv] ) scp_opt="${scp_opt} $1"; shift;;
    -[cFiloPS]    ) scp_opt="${scp_opt} $1 '$2'"; shift 2;;
    -*            ) echo "ERROR: invalid '$1' option"; exit 1;;
    *             ) break ;;
  esac
done


# determine if we want to send or receive files from the target host
if [ "$(is_target_arg "$1")" = "true" ]; then
  action='receive'
  target_host="${1%%:*}"
  target_location="${1##*:}"
  shift; # we have parsed the first argument
  local_location="$1"
  shift;
  if [ "$#" -ne 0 ]; then
    echo "ERROR: bad arguments"
    usage
  fi
else
  action='send'
  # concat files into "${files}", until the last argument
  while [ $# -ne 1 ]; do
    local_location="${local_location} $1"; shift;
  done
  if [ "$(is_target_arg "$1")" = "false" ]; then
    echo "ERROR: bad arguments"
    usage
  fi
  target_host="${1%%:*}"
  target_location="${1##*:}"
fi


[ "${action}" = 'send'    ] && eval "scp ${scp_opt} ${local_location} sshgate:${target_host}/${target_location}"
[ "${action}" = 'receive' ] && eval "scp ${scp_opt} sshgate:${target_host}/${target_location} ${local_location}"

exit 0
