#!/bin/bash
#
# Copyright (c) 2010 Linagora
# Patrick Guiran <pguiran@linagora.com>
# http://github.com/Tauop/sshGate
#
# sshGate is free software, you can redistribute it and/or modify
# it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# sshGate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


# %% __LIB_MESSAGE__ %% <-- WARNING: don't remove. used by install.sh
# %% __LIB_ASK__ %% <-- WARNING: don't remove. used by install.sh
# %% __LIB_MAIL__ %% <-- WARNING: don't remove. used by install.sh
# %% __LIB_CLI__ %% <-- WARNING: don't remove. used by install.sh
# %% __SSHGATE_CONF__ %% <-- WARNING: don't remove. used by install.sh
# %% __SSHGATE_FUNC__ %% <-- WARNING: don't remove. used by install.sh

[ -z "${__LIB_MESSAGE__}"  -a -r ./lib/message.lib.sh ] && . ./lib/message.lib.sh
[ -z "${__LIB_ASK__}"      -a -r ./lib/ask.lib.sh     ] && . ./lib/ask.lib.sh
[ -z "${__LIB_MAIL__}"     -a -r ./lib/mail.lib.sh    ] && . ./lib/mail.lib.sh
[ -z "${__LIB_CLI__}"      -a -r ./lib/cli.lib.sh     ] && . ./lib/cli.lib.sh
[ -z "${__SSHGATE_CONF__}" -a -r ./sshgate.conf       ] && . ./sshgate.conf
[ -z "${__SSHGATE_FUNC__}" -a -r ./sshgate.func       ] && . ./sshgate.func

# don't want to add exec.lib.sh in dependencies :/
user_id=`id -u`
[ "${user_id}" != "0" ] \
  && KO "You must execute $0 with root privileges"

CLI_REGISTER_MENU    'user'
CLI_REGISTER_COMMAND 'user list'           'USERS_LIST'
CLI_REGISTER_COMMAND 'user add ? key ?'    'USER_ADD \1 \2'
CLI_REGISTER_COMMAND 'user del ?'          'USER_DEL \1'

CLI_REGISTER_MENU    'user ?'
CLI_REGISTER_COMMAND 'user ? list targets'       'USER_LIST_TARGETS \1'
CLI_REGISTER_COMMAND 'user ? list usergroups'    'USER_LIST_USERGROUPS \1'
CLI_REGISTER_COMMAND 'user ? list targetgroups'  'USER_LIST_TARGETGROUPS \1'
CLI_REGISTER_COMMAND 'user ? has access ?'       'HAS_ACCESS \1 \2'
CLI_REGISTER_COMMAND 'user ? access info'        'USER_ACCESS_INFO \1'

CLI_REGISTER_MENU    'usergroup'
CLI_REGISTER_COMMAND 'usergroup list'  'USERGROUPS_LIST'
CLI_REGISTER_COMMAND 'usergroup add ?' 'USERGROUP_ADD \1'
CLI_REGISTER_COMMAND 'usergroup del ?' 'USERGROUP_DEL \1'

CLI_REGISTER_MENU    'usergroup ?'
CLI_REGISTER_COMMAND 'usergroup ? list users'        'USERGROUP_LIST_USERS \1'
CLI_REGISTER_COMMAND 'usergroup ? add user ?'        'USERGROUP_ADD_USER \1 \2'
CLI_REGISTER_COMMAND 'usergroup ? del user ?'        'USERGROUP_DEL_USER \1 \2'
CLI_REGISTER_COMMAND 'usergroup ? list targets'      'USERGROUP_LIST_TARGETS \1'
CLI_REGISTER_COMMAND 'usergroup ? list targetgroups' 'USERGROUP_LIST_TARGETGROUPS \1'

CLI_REGISTER_MENU    'target'
CLI_REGISTER_COMMAND 'target list'        'TARGETS_LIST'
CLI_REGISTER_COMMAND 'target list ?'      'TARGETS_LIST \1'
CLI_REGISTER_COMMAND 'target add ?'       'TARGET_ADD \1'
CLI_REGISTER_COMMAND 'target add ? key ?' 'TARGET_ADD \1 \2'
CLI_REGISTER_COMMAND 'target del ?'       'TARGET_DEL \1'

CLI_REGISTER_MENU    'target alias'
CLI_REGISTER_COMMAND 'target alias list'  'TARGET_LIST_ALIASES'
CLI_REGISTER_COMMAND 'target alias del ?' 'TARGET_DEL_ALIAS \1'

CLI_REGISTER_MENU    'target ssh'
CLI_REGISTER_COMMAND 'target ssh test all'        'TARGET_SSH_TEST_ALL'
CLI_REGISTER_COMMAND 'target ssh install key all' 'TARGET_SSH_INSTALL_ALL_KEYS'

CLI_REGISTER_MENU    'target ?'
CLI_REGISTER_COMMAND 'target ? realname'        'TARGET_REAL \1'
CLI_REGISTER_COMMAND 'target ? add alias ?'     'TARGET_ADD_ALIAS \1 \2'
CLI_REGISTER_COMMAND 'target ? del alias ?'     'TARGET_DEL_ALIAS \2'
CLI_REGISTER_COMMAND 'target ? list aliases'    'TARGET_LIST_ALIASES \1'
CLI_REGISTER_COMMAND 'target ? ssh test'        'TARGET_SSH_TEST \1'
CLI_REGISTER_COMMAND 'target ? ssh install key' 'TARGET_SSH_INSTALL_KEY \1'

CLI_REGISTER_MENU    'target ? access'
CLI_REGISTER_COMMAND 'target ? access info'             'TARGET_ACCESS_INFO \1'
CLI_REGISTER_COMMAND 'target ? access list users'       'TARGET_ACCESS_LIST_USERS \1'
CLI_REGISTER_COMMAND 'target ? access add user ?'       'TARGET_ACCESS_ADD_USER \1 \2'
CLI_REGISTER_COMMAND 'target ? access del user ?'       'TARGET_ACCESS_DEL_USER \1 \2'
CLI_REGISTER_COMMAND 'target ? access list usergroups'  'TARGET_ACCESS_LIST_USERGROUPS \1'
CLI_REGISTER_COMMAND 'target ? access add usergroup ?'  'TARGET_ACCESS_ADD_USERGROUP \1 \2'
CLI_REGISTER_COMMAND 'target ? access del usergroup ?'  'TARGET_ACCESS_DEL_USERGROUP \1 \2'

CLI_REGISTER_MENU    'targetgroup'
CLI_REGISTER_COMMAND 'targetgroup list'           'TARGETGROUPS_LIST'
CLI_REGISTER_COMMAND 'targetgroup add ?'          'TARGETGROUP_ADD \1'
CLI_REGISTER_COMMAND 'targetgroup del ?'          'TARGETGROUP_DEL \1'
CLI_REGISTER_COMMAND 'targetgroup ? list targets' 'TARGETGROUP_LIST_TARGETS \1'
CLI_REGISTER_COMMAND 'targetgroup ? add target ?' 'TARGETGROUP_ADD_TARGET \1 \2'
CLI_REGISTER_COMMAND 'targetgroup ? del target ?' 'TARGETGROUP_DEL_TARGET \1 \2'

CLI_REGISTER_MENU    'targetgroup ?'
CLI_REGISTER_MENU    'targetgroup ? access'
CLI_REGISTER_COMMAND 'targetgroup ? access list users'      'TARGETGROUP_ACCESS_LIST_USERS \1'
CLI_REGISTER_COMMAND 'targetgroup ? access add user ?'      'TARGETGROUP_ACCESS_ADD_USER \1 \2'
CLI_REGISTER_COMMAND 'targetgroup ? access del user ?'      'TARGETGROUP_ACCESS_DEL_USER \1 \2'
CLI_REGISTER_COMMAND 'targetgroup ? access list usergroups' 'TARGETGROUP_ACCESS_LIST_USERGROUPS \1'
CLI_REGISTER_COMMAND 'targetgroup ? access add usergroup ?' 'TARGETGROUP_ACCESS_ADD_USERGROUP \1 \2'
CLI_REGISTER_COMMAND 'targetgroup ? access del usergroup ?' 'TARGETGROUP_ACCESS_DEL_USERGROUP \1 \2'


CLI_REGISTER_KCOMMAND 'help' 'HELP_LIST'

CLI_REGISTER_COMMAND 'save' 'SETUP_SSHGATE_GATE_ACCOUNT'

HELP_LIST () {
  MSG_INDENT_INC
  MSG "= Users ="
  MSG_INDENT_INC
    MESSAGE "user list                                 - List all users"
    MESSAGE "user add <username> key <sshkey-file>     - add a new user"
    MESSAGE "user del <username>                       - delete a user"
    MESSAGE "user <username> list groups               - list group of user"
    MESSAGE "user <username> list targets              - list targets hosts of user"
    MESSAGE "user <username> has access <target-name>  - tell if a user has access to a target host"
    MESSAGE "user <username> access info               - list all target user has access to, and how"
  MSG_INDENT_DEC
  BR

  MSG "= User's Group ="
  MSG_INDENT_INC
    MESSAGE "usergroup list                              - list all users groups"
    MESSAGE "usergroup add <group-name>                  - create a users group"
    MESSAGE "usergroup del <group-name>                  - delete a users group"
    MESSAGE "usergroup <group-name> list [users]         - list users of a group"
    MESSAGE "usergroup <group-name> add user <username>  - add an user into a group"
    MESSAGE "usergroup <group-name> del user <username>  - delete an user from a group"
  MSG_INDENT_DEC
  BR

  MSG "= Target ="
  MSG_INDENT_INC
    MESSAGE "target list [<pattern>]                      - list all targets, whose name match <pattern> if given"
    MESSAGE "target add <target-name>                     - add a new target host, and generate a private sshkey"
    MESSAGE "target add <target-name> key <sshkey-file>   - add a new target host, with a given private sshkey"
    MESSAGE "target del <target-name>                     - delete a target host"
    MESSAGE "target alias list                            - list all aliases of a target host"
    MESSAGE "target alias del <alias-name>                - delete an alias name"
    MESSAGE "target ssh test all                          - test to ssh connectivity for all targets"
    MESSAGE "target ssh install all keys                  - install public sshkey on all targets"
    MESSAGE "target <target-name> realname                - print the real name of a target host"
    MESSAGE "target <target-name> add alias <alias-name>  - add an alias of target hostname"
    MESSAGE "target <target-name> del alias <alias-name>  - delete an alias of the target"
    MESSAGE "target <target-name> list aliases            - list aliases of the target host"
    MESSAGE "target <target-name> access info             - list all user who has access to target, and how"
    MESSAGE "target <target-name> ssh test                - test ssh connectivity for the target host"
    MESSAGE "target <target-name> ssh install key          - install sshkey on the target host"
  MSG_INDENT_DEC
  BR

  MSG "= Target's Group ="
  MSG_INDENT_INC
    MESSAGE "targetgroup list                                         - list all targets' groups"
    MESSAGE "targetgroup add <targetgroup-name>                       - add a new target group"
    MESSAGE "targetgroup del <targetgroup-name>                       - delete a target group"
    MESSAGE "targetgroup <targetgroup-name> list targets              - list all targets hosts for the targetgroup"
    MESSAGE "targetgroup <targetgroup-name> add target <target-name>  - add a target host to the targetgroup"
    MESSAGE "targetgroup <targetgroup-name> del target <target-name>  - delete a target host from the targetgroup"
  MSG_INDENT_DEC
  BR

  MSG "= Target's Access ="
  MSG_INDENT_INC
    MESSAGE "target <target-name> access list users                  - list all users who can access to the target host"
    MESSAGE "target <target-name> access add user <user-name>        - give user access to a target host"
    MESSAGE "target <target-name> access del user <user-name>        - revoke user access of target host"
    MESSAGE "target <target-name> access list usergroups             - list all groups who can access to the target host"
    MESSAGE "target <target-name> access add usergroup <group-name>  - give group access to a target host"
    MESSAGE "target <target-name> access del usergroup <group-name>  - revoke group access of a target host"
  MSG_INDENT_DEC
  BR

  MSG "= Targets' Group's Access ="
  MSG_INDENT_INC
    MESSAGE "targetgroup <targetgroup-name> access list users                     - list all users who can access to the targetgroup"
    MESSAGE "targetgroup <targetgroup-name> access add user <user-name>           - give user acess to the targetgroup"
    MESSAGE "targetgroup <targetgroup-name> access del user <user-name>           - revoke user access to the targetgroup"
    MESSAGE "targetgroup <targetgroup-name> access list usergroups                - list all usergroup who can access to the targetgroup"
    MESSAGE "targetgroup <targetgroup-name> access add usergroup <usergroup-name> - give usergroup access to the targetgroup"
    MESSAGE "targetgroup <targetgroup-name> access del usergroup <usergroup-name> - revoke usergroup access to the targetgroup"
  MSG_INDENT_DEC
  BR

  MSG "= Misc ="
  MSG_INDENT_INC
    MESSAGE "save             - forge re-write of sshgate account ./ssh/authorized_keys2 file"
    MESSAGE "quit             - exit the current CLI context menu, or exit the CLI"
    MESSAGE "exit             - exit the CLI"
  MSG_INDENT_DEC
  BR

  MSG_INDENT_DEC
}

MSG "sshGate administration Interface"
MSG "By Patrick Guiran <pguiran@linagora.com>"
BR
MSG "Use 'help' command to list all avariable commands"
BR

CLI_USE_READLINE --history-file ~/.sshgate_history
CLI_SET_PROMPT "sshGate"

[ ${SSHGATE_MAIL_SEND:-} = 'true' ] && MAIL_CREATE ${SSHGATE_MAIL_TMP_FILE}

CLI_RUN

[ ${SSHGATE_MAIL_SEND:-} = 'true' ] \
  && MAIL_SEND "${SSHGATE_MAIL_SUBJECT}" "${SSHGATE_MAIL_TO}"
[ $? -eq 2 ] && NOTICE "No modification noticed. Repport e-mail will not be sent"
