#!/bin/bash
#
# Copyright (c) 2010 Linagora
# Patrick Guiran <pguiran@linagora.com>
# http://github.com/Tauop/sshGate
#
# sshGate is free software, you can redistribute it and/or modify
# it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# sshGate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


# %% __LIB_MESSAGE__ %% <-- WARNING: don't remove. used by install.sh
# %% __LIB_ASK__ %% <-- WARNING: don't remove. used by install.sh
# %% __LIB_MAIL__ %% <-- WARNING: don't remove. used by install.sh
# %% __LIB_CLI__ %% <-- WARNING: don't remove. used by install.sh
# %% __SSHGATE_CONF__ %% <-- WARNING: don't remove. used by install.sh
# %% __SSHGATE_FUNC__ %% <-- WARNING: don't remove. used by install.sh
# %% __CLI_HELP_SH__ %% <-- WARNING: don't remove. used by install.sh

[ -z "${__LIB_MESSAGE__}"  -a -r ./lib/message.lib.sh ] && . ./lib/message.lib.sh
[ -z "${__LIB_ASK__}"      -a -r ./lib/ask.lib.sh     ] && . ./lib/ask.lib.sh
[ -z "${__LIB_MAIL__}"     -a -r ./lib/mail.lib.sh    ] && . ./lib/mail.lib.sh
[ -z "${__LIB_CLI__}"      -a -r ./lib/cli.lib.sh     ] && . ./lib/cli.lib.sh
[ -z "${__SSHGATE_CONF__}" -a -r ./sshgate.conf       ] && . ./sshgate.conf
[ -z "${__SSHGATE_FUNC__}" -a -r ./sshgate.func       ] && . ./sshgate.func

SSHKEY_USER=
while true ; do
  [ $# -eq 0 ] && break;
  case $1 in
    -u ) shift; SSHKEY_USER="$1"; shift ;;
    *  ) shift ;; # ignore
  esac
done

if [ -z "${SSHKEY_USER}" ]; then
  echo "ERROR: you have to specify a username to use sshgate CLI"
  echo "usage: $0 -u <username>"
  exit 1
fi

# don't want to add exec.lib.sh in dependencies :/
user_id=`id -u`
[ "${user_id}" != "0" ] \
  && KO "You must execute $0 with root privileges"

CLI_REGISTER_MENU    'user'
CLI_REGISTER_COMMAND 'user list'           'USERS_LIST'
CLI_REGISTER_COMMAND 'user add ? key ?'    'USER_ADD \1 \2'
CLI_REGISTER_COMMAND 'user del ?'          'USER_DEL \1'

CLI_REGISTER_MENU    'user ?'
CLI_REGISTER_COMMAND 'user ? display conf'       'USER_DISPLAY_CONF \1'
CLI_REGISTER_COMMAND 'user ? set conf ? ?'       'USER_SET_CONF \1 \2 \3'
CLI_REGISTER_COMMAND 'user ? list targets'       'USER_LIST_TARGETS \1'
CLI_REGISTER_COMMAND 'user ? list usergroups'    'USER_LIST_USERGROUPS \1'
CLI_REGISTER_COMMAND 'user ? has access ?'       'HAS_ACCESS \1 \2'
CLI_REGISTER_COMMAND 'user ? access info'        'USER_ACCESS_INFO \1'
CLI_REGISTER_COMMAND 'user ? access notify'      'USER_ACCESS_NOTIFY \1'

CLI_REGISTER_MENU    'usergroup'
CLI_REGISTER_COMMAND 'usergroup list'  'USERGROUPS_LIST'
CLI_REGISTER_COMMAND 'usergroup add ?' 'USERGROUP_ADD \1'
CLI_REGISTER_COMMAND 'usergroup del ?' 'USERGROUP_DEL \1'

CLI_REGISTER_MENU    'usergroup ?'
CLI_REGISTER_COMMAND 'usergroup ? list users'        'USERGROUP_LIST_USERS \1'
CLI_REGISTER_COMMAND 'usergroup ? add user ?'        'USERGROUP_ADD_USER \1 \2'
CLI_REGISTER_COMMAND 'usergroup ? del user ?'        'USERGROUP_DEL_USER \1 \2'
CLI_REGISTER_COMMAND 'usergroup ? list targets'      'USERGROUP_LIST_TARGETS \1'
CLI_REGISTER_COMMAND 'usergroup ? access info'       'USERGROUP_ACCESS_INFO \1'

CLI_REGISTER_MENU    'target'
CLI_REGISTER_COMMAND 'target list'        'TARGETS_LIST'
CLI_REGISTER_COMMAND 'target list ?'      'TARGETS_LIST \1'
CLI_REGISTER_COMMAND 'target add ?'       'TARGET_ADD \1'
CLI_REGISTER_COMMAND 'target add ? key ?' 'TARGET_ADD \1 \2'
CLI_REGISTER_COMMAND 'target del ?'       'TARGET_DEL \1'

CLI_REGISTER_MENU    'target alias'
CLI_REGISTER_COMMAND 'target alias list'  'TARGET_LIST_ALIASES'
CLI_REGISTER_COMMAND 'target alias del ?' 'TARGET_DEL_ALIAS \1'

CLI_REGISTER_MENU    'target ssh'
CLI_REGISTER_COMMAND 'target ssh test all'        'TARGET_SSH_TEST_ALL'
CLI_REGISTER_COMMAND 'target ssh install key all' 'TARGET_SSH_INSTALL_ALL_KEYS'

CLI_REGISTER_MENU    'target ?'
CLI_REGISTER_COMMAND 'target ? rename ?'        'TARGET_RENAME \1 \2'
CLI_REGISTER_COMMAND 'target ? realname'        'TARGET_REAL \1'
CLI_REGISTER_COMMAND 'target ? add alias ?'     'TARGET_ADD_ALIAS \1 \2'
CLI_REGISTER_COMMAND 'target ? del alias ?'     'TARGET_DEL_ALIAS \2'
CLI_REGISTER_COMMAND 'target ? list aliases'    'TARGET_LIST_ALIASES \1'

CLI_REGISTER_COMMAND 'target ? display conf'     'TARGET_DISPLAY_CONF \1'
CLI_REGISTER_COMMAND 'target ? set conf ? ?'     'TARGET_SET_CONF \1 \2 \3'

CLI_REGISTER_COMMAND 'target ? ssh test'         'TARGET_SSH_TEST \1'
CLI_REGISTER_COMMAND 'target ? ssh install key'  'TARGET_SSH_INSTALL_KEY \1'
CLI_REGISTER_COMMAND 'target ? ssh use default'  'TARGET_SSH_USE_DEFAULT_KEY \1'
CLI_REGISTER_COMMAND 'target ? ssh list logins'  'TARGET_SSH_LIST_LOGINS \1'
CLI_REGISTER_COMMAND 'target ? ssh add login ?'  'TARGET_SSH_ADD_LOGIN \1 \2'
CLI_REGISTER_COMMAND 'target ? ssh del login ?'  'TARGET_SSH_DEL_LOGIN \1 \2'
CLI_REGISTER_COMMAND 'target ? ssh list options' 'TARGET_GET_SSH_OPTIONS \1'
CLI_REGISTER_COMMAND 'target ? scp list options' 'TARGET_GET_SCP_OPTIONS \1'

CLI_REGISTER_MENU    'target ? access'
CLI_REGISTER_COMMAND 'target ? access info'             'TARGET_ACCESS_INFO \1'
CLI_REGISTER_COMMAND 'target ? access list users'       'TARGET_ACCESS_LIST_USERS \1'
CLI_REGISTER_COMMAND 'target ? access add user ?'       'TARGET_ACCESS_ADD_USER \1 \2'
CLI_REGISTER_COMMAND 'target ? access del user ?'       'TARGET_ACCESS_DEL_USER \1 \2'
CLI_REGISTER_COMMAND 'target ? access list usergroups'  'TARGET_ACCESS_LIST_USERGROUPS \1'
CLI_REGISTER_COMMAND 'target ? access add usergroup ?'  'TARGET_ACCESS_ADD_USERGROUP \1 \2'
CLI_REGISTER_COMMAND 'target ? access del usergroup ?'  'TARGET_ACCESS_DEL_USERGROUP \1 \2'

CLI_REGISTER_KCOMMAND 'help'   'SHOW_HELP'
CLI_REGISTER_KCOMMAND 'help ?' 'SHOW_HELP \1'
CLI_REGISTER_KCOMMAND 'help ? ?' 'SHOW_HELP \1 \2'


CLI_REGISTER_COMMAND 'build authorized_keys' 'BUILD_AUTHORIZED_KEYS'
CLI_REGISTER_COMMAND 'build known_hosts'     'BUILD_KNOWN_HOSTS'


MSG "sshGate administration Interface"
MSG "By Patrick Guiran <pguiran@linagora.com>"
BR
MSG "Use 'help' command to list all avariable commands"
BR

# use --force when CLI is called from remote
CLI_USE_READLINE --force --history-file ~/.sshgate_history
CLI_SET_PROMPT "sshGate"

[ ${SSHGATE_MAIL_SEND:-} = 'true' ] && MAIL_CREATE

CLI_RUN

[ ${SSHGATE_MAIL_SEND:-} = 'true' ] \
  && MAIL_SEND "${SSHGATE_MAIL_SUBJECT} (${SSHKEY_USER})" "${SSHGATE_MAIL_TO}"
[ $? -eq 2 ] && NOTICE "No modification noticed. Repport e-mail will not be sent"
